#github授权登陆参数
github:
  redirect_url: http://localhost:8080/callback
  client:
    id: 6c68986ba20538ae6802
    secret: 974bd9951d0de64cb679a61840c8959cd4dc8188

#debug: true
spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
#开启mybatis日志输出
logging:
  level:
    com:
      yang:
        mj:
          mapper: debug
mybatis:
  type-aliases-package: com.yang.mj.Entity
  configuration:
    map-underscore-to-camel-case: true
